services:
  # PostgreSQL Database
  - type: pserv
    name: heartlink-database
    env: docker
    plan: starter
    database: heartlink_db
    user: heartlink_user

  # Web Service (Backend + Frontend)
  - type: web
    name: heartlink-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: heartlink-database
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPL_ID
        sync: false
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: REPLIT_DOMAINS
        sync: false